#!/bin/bash
# 自然数を２つ引数にとって、最大公約数を標準出力に出力

# 引数の数のチェック
if [ "$#" -ne "2" ] ; then
   echo "自然数（1以上の整数）を２つ入力して下さい"
   exit 1
fi
# 引数の大きい方をa,小さい方をbにセットする
if [ "${1}" -ge "${2}" ] ; then
   a=${1}
   b=${2}
#   echo "a = ${a}, b = ${b}"
else
   a=${2}
   b=${1}
#   echo "a = ${a}, b = ${b}"
fi
# 0以下のチェック
if [ ${b} -le "0" ] ; then
  echo "自然数（1以上の整数）を入力して下さい"
  exit 1
fi

# 1回目の計算.whileループの外。bがaの最大公約数(余り0)のときは
# bを標準出力出力し、exitする
r=$(( ${a} % ${b} ))
#echo "最初のr = ${r}"
if [ ${r} -eq "0" ] ; then
  echo ${b}
  exit 0
fi

# 1回目で求まらない時は新a=b,新b=rとして余りが0になるまで繰り返す
while [ "${r}" -ne "0" ] ; do
  a=${b}
  b=${r}
  r=$(( ${a} % ${b} ))
done

echo ${b}
exit 0

